// Generated by CoffeeScript 1.9.2
(function() {
  engine.addPrefab("platform", {
    constructor: function(args) {
      this.body = new Engine.PhysicsBody(engine, {
        x: args.x,
        y: args.y,
        width: args.width,
        height: args.height,
        depth: 10,
        density: 10,
        drag: 1,
        friction: 0.1
      });
      return this.force = 23;
    },
    update: function(entities) {
      return this.body.update(engine);
    },
    draw: function(fab, can) {
      return can.add(new fab.Rect({
        width: this.body.width,
        height: this.body.height,
        left: this.body.pos.x,
        top: this.body.pos.y
      }));
    }
  });

}).call(this);
