// Generated by CoffeeScript 1.9.2
(function() {
  engine.addPrefab("player", {
    constructor: function(args) {
      this.body = new Engine.PhysicsBody(engine, {
        x: args.x,
        y: args.y,
        width: 10,
        height: 10,
        depth: 10,
        density: 10,
        drag: 1.05,
        friction: 0.01
      });
      this.force = 23;
      this.jumpForce = 0.8;
      return this.isOnGround = false;
    },
    update: function(entities) {
      var collisionElement;
      if (engine.keyPressed("down")) {
        this.body.applyForce(0, this.force);
      }
      if (engine.keyPressed("left")) {
        this.body.applyForce(-this.force, 0);
      }
      if (engine.keyPressed("right")) {
        this.body.applyForce(this.force, 0);
      }
      this.isOnGround = false;
      collisionElement = void 0;
      entities.forEach((function(_this) {
        return function(entity) {
          if (entity.type === "platform" && _this.body.collidesWith(entity.body)) {
            _this.isOnGround = true;
            if (_this.body.vel.y > 0) {
              _this.body.vel.y = 0;
            }
            _this.body.pos.y = entity.body.pos.y - _this.body.height;
            return collisionElement = entity;
          }
        };
      })(this));
      if (this.isOnGround && engine.keyPressed("up")) {
        this.isOnGround = false;
        this.body.pos.y -= 1;
        this.body.impulse(0, -this.jumpForce);
      }
      this.body.update();
      if (!this.isOnGround) {
        this.body.gravity();
      }
      if (this.isOnGround) {
        return this.body.frictionX();
      }
    },
    draw: function(fab, can) {
      return can.add(new fab.Rect({
        width: this.body.width,
        height: this.body.height,
        left: this.body.pos.x,
        top: this.body.pos.y
      }));
    }
  });

}).call(this);
